cart/urls.py
from django.urls import path

from cart import views
from cart.views import CartAddView, CartRemoveView

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:product_slug>/', CartAddView.as_view(), name='cart_add'),
    path('remove/<slug:product_slug>/', CartRemoveView.as_view(), name='cart_remove'),
]

marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_user.views import RegistrationNewUser
from django.conf import settings
from django.conf.urls.static import static
from main_app.views import MarketplaceListView, page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MarketplaceListView.as_view(), name="main_page"),
    path('user/', include('custom_user.urls', namespace='user')),
    path('product/', include('product.urls', namespace='product')),
    path('marketplace/', include('main_app.urls', namespace='marketplace')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from product.models import Product
from main_app.exceptions import ValidationError


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        if 'slug' in kwargs:
            self.product_slug = kwargs.pop('slug')
        return super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('quantity'):
            raise forms.ValidationError('You need type the quantity!')
        quantity = cleaned_data.get('quantity')
        if quantity < 1:
            raise forms.ValidationError('You need type the positive integer!')
        try:
            product = Product.objects.get(slug=self.product_slug)
            if quantity > product.quantity:
                raise forms.ValidationError('You have ordered more than products available!')

        except Product.DoesNotExist:
            raise forms.ValidationError("Required fild is absence!")




cart/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, FormView, DeleteView

from main_app.permission_mixins import UserLoginRequiredMixin
from product.models import Product
from cart.cart import Cart
from cart.forms import CartAddProductForm


class CartAddView(UserLoginRequiredMixin, FormView):
    template_name = 'cart/detail.html'
    # queryset = Product.objects.all()
    form_class = CartAddProductForm
    success_url = '/cart'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request,
                       'slug': self.kwargs['product_slug']})
        return kwargs

    def form_valid(self, form):
        product_slug = self.kwargs.get('product_slug') or self.request.GET.get('product_slug')
        obj = Product.objects.get(slug=product_slug)
        cart = Cart(self.request)
        cd = form.cleaned_data
        cart.add(product=obj,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
        obj.quantity -= form.cleaned_data['quantity']
        obj.save()
        return super().form_valid(form=form)

    def form_invalid(self, form):
        product_slug = self.kwargs['product_slug']
        return HttpResponseRedirect(f'/product/detail/{product_slug}')



class CartRemoveView(UserLoginRequiredMixin, DeleteView):    
    slug_url_kwarg = 'slug'
    template_name = 'cart/detail.html'
    success_url = '/cart/detail/'
    queryset = Product.objects.all()

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        slug = self.kwargs.get('product_slug') or self.request.GET.get('product_slug')
        queryset = queryset.filter(slug=slug)
        obj = queryset.get()
        cart = Cart(self.request)
        cart.remove(obj)

        return obj


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

 {% block header %}
     Your shopping cart
 {% endblock %}

{% block content %}

      <h1>Your shopping cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" product.slug %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "main_page" %}" class="button
    light">Continue shopping</a>

  </p>

{% endblock %}

 {% block pagination %}
 {% endblock %}