cart/urls.py
from django.urls import path

from cart import views
from cart.views import CartAddView, CartRemoveView

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:product_slug>/', CartAddView.as_view(), name='cart_add'),
    path('remove/<slug:product_slug>/', CartRemoveView.as_view(), name='cart_remove'),
]

custom_user/urls.py
from django.urls import path
from custom_user.views import RegistrationNewUser

app_name = 'user'

urlpatterns = [
    path('registration/', RegistrationNewUser.as_view(), name="registration"),
    #path('registration/', RegistrationNewUser.as_view(), name="registration"),

]

main_app/urls.py
from django.urls import path
from main_app.views import LoginUser, LogoutUser, ProductCategory

app_name = 'marketplace'

urlpatterns = [
    path('login/', LoginUser.as_view(), name="login"),
    path('logout/', LogoutUser.as_view(), name="logout"),
    path('category/<slug:category_slug>/', ProductCategory.as_view(), name='category'),
]

marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_user.views import RegistrationNewUser
from django.conf import settings
from django.conf.urls.static import static
from main_app.views import MarketplaceListView, page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MarketplaceListView.as_view(), name="main_page"),
    path('user/', include('custom_user.urls', namespace='user')),
    path('product/', include('product.urls', namespace='product')),
    path('marketplace/', include('main_app.urls', namespace='marketplace')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name']), ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('marketplace:category', kwargs={'category_slug': self.slug})

































product/models.py
from django.db import models
from main_app.models import Category
from custom_user.models import CustomUser
from django.urls import reverse

# Create your models here.


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    seller = models.ForeignKey(CustomUser, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    model = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    # ОГРАНИЧИТЬ ДЛИНУ?
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    promotion = models.BooleanField(default=False)

    class Meta:
        ordering = ['title']
        indexes = [models.Index(fields=['id', 'slug']),
                   models.Index(fields=['title']),
                   models.Index(fields=['-created'])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product:detail_product', kwargs={'product_slug': self.slug})


templates/marketplace/category.html
{% extends 'base.html' %}
{% load static %}

    {% block header %}
    <h2>Category</h2>
    {% endblock %}


{% block urls %}
     <form method="get">
        {{ sort }}
        <input type="submit" value="Sort">
    </form>
 {% endblock %}

  {% block content %}

      {% for product in product_list %}
              <div class="item" style="float: left; position: relative; width: 10%; margin: 1.66%; ">
              <a href="{{ product.get_absolute_url }}">{{ product.title }}<br>
              <img style="max-width: 100px; max-height: 100px" src="{% if product.image %}{{ product.image.url }}
              {% else %} {% static "img/no_image.png" %}
              {% endif %}"></a><br>
              ${{ product.price }}<br><br></div>
              {% endfor %}






       {% for category in category_list %}
        	{% if category.pk == category_selected %}
		        <li class="selected">{{category.name}}</li>
	        {% else %}
		        <li><a href="{{ c.get_absolute_url }}">{{category.name}}</a></li>
	        {% endif %}
       {% endfor %}
  {% endblock %}

 {% block pagination %}
 {% endblock %}




templates/marketplace/login.html
{% extends 'base.html' %}

    {% block header %}
    <h2>Page to Login</h2>
    {% endblock %}


{% block urls %}
    <div>
        <a href="{% url 'user:registration' %}">Registration of new user</a>
    </div>
{% endblock %}

  {% block content %}
      <div>
          <form method="post" action="{% url 'marketplace:login' %}">
          {% csrf_token %}
          {{ form }}
          <button type="submit">Login</button>
          </form>
          <br><br>
          <a href="{% url 'user:registration' %}">Registration of new user</a>
      </div>
  {% endblock %}

 {% block pagination %}
 {% endblock %}


templates/marketplace/main.html
{% extends 'base.html' %}
{% load static %}


    {% block header %}
    {% endblock %}


    {% block urls %}

              <li class="logo"><a href="{% url 'main_page' %}"><div class="logo"></div></a></li>
              {% for m in menu %}
		      <li><a href="{% url m.url_name %}">{{m.title}}</a></li>
               {% endfor %}

         <h3> Search </h3>
              <form action="{% url 'main_page' %}">
              <label><input type="text" name="search_text"></label>
              <input type="submit" value="Search">
              <form action="{% url 'main_page' %}"><button>Clear</button></form>
              </form>
              <br><br>

    {% endblock %}


{% block content %}


    <div id="sidebar">
    <ul id="left-chapters">
        <h3>Categories</h3>
             {% for category in categories %}
             <li {% if category.slug == c.slug %}class="selected"{% endif %}>
             <a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
      {% endfor %}
    </ul>
    </div>

    <div>

           <div id="product">
           <h3>Hot new product</h3>
              {% for product in product_list %}
              <div class="item" style="float: left; position: relative; width: 3cm; margin: 1.66%; ">
              <a href="{{ product.get_absolute_url }}">{{ product.title }} <br>
              <img style="max-width: 100px; max-height: 100px" src="{% if product.image %}{{ product.image.url }}
              {% else %} {% static "img/no_image.png" %}
              {% endif %}"></a><br>
              ${{ product.price }}<br><br></div>
              {% endfor %}
           </div>

           <div id="promotional">
           <h3>Promotional offers</h3>
              {% for product in product_list %}
              {% if product.promotion == True %}
              <div class="item" style="float: left; position: relative; width: 12%; margin: 1.66%; ">
              <a href="{{ product.get_absolute_url }}">{{ product.title }}<br>
              <img style="max-width: 100px; max-height: 100px" src="{% if product.image %}{{ product.image.url }}
              {% else %} {% static "img/no_image.png" %}
              {% endif %}"></a><br>
              ${{ product.price }}<br><br></div>
              {% endif %}
              {% endfor %}
           </div>

    </div>

{% endblock %}


 {% block pagination %}
 {% endblock %}
