cart/urls.py
from django.urls import path

from cart import views
from cart.views import CartAddView, CartRemoveView

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:product_slug>/', CartAddView.as_view(), name='cart_add'),
    path('remove/<slug:product_slug>/', CartRemoveView.as_view(), name='cart_remove'),
]

comment/urls.py
from django.urls import path
from comment.views import CommentCreateView

app_name = 'comment'

urlpatterns = [
    path('create/<int:product_id>/', CommentCreateView.as_view(), name="create_comment"),
    #path('change/<int:pk>/', CommentUpdateView.as_view(), name="change_product"),
    #path('delete/<int:pk>/', CommentDeleteView.as_view(), name="detail_product"),

]


favorites/urls.py
from django.urls import path
from favorites.views import FavoritesCreateView, FavoritesListView, FavoritesDeleteView

app_name = 'favorites'

urlpatterns = [
    path('create/<slug:product_slug>/', FavoritesCreateView.as_view(), name="create_favorites"),
    path('list/', FavoritesListView.as_view(), name="list_favorites"),
    path('delete/<int:pk>/', FavoritesDeleteView.as_view(), name="delete_favorites"),
]


marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_user.views import RegistrationNewUser
from django.conf import settings
from django.conf.urls.static import static
from main_app.views import MarketplaceListView, page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MarketplaceListView.as_view(), name="main_page"),
    path('user/', include('custom_user.urls', namespace='user')),
    path('product/', include('product.urls', namespace='product')),
    path('marketplace/', include('main_app.urls', namespace='marketplace')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

product/urls.py
from django.urls import path
from product.views import ProductCreateView, UpdateProductView, ProductDetailView, ProductDeleteView

app_name = 'product'

urlpatterns = [
    path('create/', ProductCreateView.as_view(), name="create_product"),
    path('change/<slug:product_slug>/', UpdateProductView.as_view(), name="change_product"),
    path('detail/<slug:product_slug>/', ProductDetailView.as_view(), name="detail_product"),
    path('delete/<slug:product_slug>/', ProductDeleteView.as_view(), name="delete_product"),
]


product/models.py
from django.db import models
from main_app.models import Category
from custom_user.models import CustomUser
from django.urls import reverse

# Create your models here.


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    seller = models.ForeignKey(CustomUser, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    model = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    # ОГРАНИЧИТЬ ДЛИНУ?
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    promotion = models.BooleanField(default=False)

    class Meta:
        ordering = ['title']
        indexes = [models.Index(fields=['id', 'slug']),
                   models.Index(fields=['title']),
                   models.Index(fields=['-created'])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product:detail_product', kwargs={'product_slug': self.slug})


product/forms.py
from django import forms
from django.contrib import messages
from product.models import Product
from main_app.models import Category
from custom_user.models import CustomUser
from main_app.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class ProductCreationForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['category', 'title', 'model', 'image', 'quantity', 'description', 'price']

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        if 'slug' in kwargs:
            self.category_id = kwargs.pop('slug')
        return super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        try:            
            if not cleaned_data.get('category'):
                self.add_error('category', "The category field Error!")
                messages.error(self.request, 'You must type the category!')
                raise forms.ValidationError('This field is required!')
            if not cleaned_data.get('title'):
                self.add_error('title', "The title field Error!")
                messages.error(self.request, 'You must type the title!')
                raise forms.ValidationError('This field is required!')
            if not cleaned_data.get('description'):
                self.add_error('description', "The description field Error!")
                messages.error(self.request, 'You must type the description!')
                raise forms.ValidationError('This field is required!')
            if not cleaned_data.get('price'):
                self.add_error('price', "The price field Error!")
                messages.error(self.request, 'You must type the price!')
                raise forms.ValidationError('This field is required!')

            title = self.cleaned_data.get('title')
            description = self.cleaned_data.get('description')
            price = self.cleaned_data.get('price')

            if len(title) <= 5:
                self.add_error('title', 'The title field Error!')
                messages.error(self.request, 'The title field must be more then 5 symbol!')
            if len(description) <= 8:
                self.add_error('description', 'The description field Error!')
                messages.error(self.request, 'The description must be more then 8 symbol!')
            if price < 1:
                self.add_error('price', 'The price field Error!')
                messages.error(self.request, 'The price must be more then 0!')

        except Category.DoesNotExist:
            self.add_error(None, 'The object existing Error!')
            messages.error(self.request, 'This category does not exist!')
        except CustomUser.DoesNotExist:
            self.add_error(None, 'The object existing Error!')
            messages.error(self.request, 'This user does not exist!')















product/views.py
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from django.utils.translation import gettext_lazy as _
from comment.models import Comment
from main_app.permission_mixins import UserLoginRequiredMixin
from product.forms import ProductCreationForm
from cart.forms import CartAddProductForm
from product.models import Product
from main_app.models import Category
from comment.forms import CommentCreationForm


# Create your views here.


class ProductCreateView(UserLoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductCreationForm
    success_url = '/'
    template_name = 'product/create.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.seller = self.request.user
        obj.slug = slugify(obj.title)
        obj.save()
        return super().form_valid(form=form)

    def form_invalid(self, form):
        return HttpResponseRedirect('/product/create/')


class UpdateProductView(UserLoginRequiredMixin, UpdateView):
    """
    View for changing exists MovieSession object. Subclasses SuperUserRequiredMixin
    to ensure that only superusers can update MovieSession objects.
    """
    model = Product
    form_class = ProductCreationForm
    success_url = '/'
    template_name = 'product/change.html'
    # slug_field = 'url'
    slug_url_kwarg = 'product_slug'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'request': self.request,
            'slug': self.kwargs['product_slug']
        })
        return kwargs

    def get_queryset(self):
        """
        The method is overridden so that the authenticated user receives information only about himself
        :return: filtered by a specific user queryset
        """
        return super().get_queryset().filter(seller=self.request.user)


class ProductDetailView(UserLoginRequiredMixin, DetailView):
    """
    A view that displays the details of a single Product.
    A form with a tickets purchase is also available on the page.
    Subclasses UserLoginRequiredMixin to ensure that only authenticated user has access to the page.
    """
    model = Product
    template_name = 'product/detail.html'
    slug_url_kwarg = 'product_slug'
    extra_context = {"purchase_form": CartAddProductForm(),
                     "comment_form": CommentCreationForm()}

    def get_object(self, queryset=None):
        """
        The method overridden to get a specific Product object
        :param queryset:
        :return: Product object
        """
        if queryset is None:
            queryset = self.get_queryset()
        product_slug = self.kwargs.get('product_slug') or self.request.GET.get('product_slug')
        queryset = queryset.filter(slug=product_slug)
        obj = queryset.get()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_slug = self.kwargs.get('product_slug') or self.request.GET.get('product_slug')
        get_product = Product.objects.get(slug=product_slug)
        get_comment = Comment.objects.filter(to_product=get_product.id)
        context.update({'comments': get_comment})
        return context


class ProductDeleteView(UserLoginRequiredMixin, DeleteView):
    model = Product
    slug_url_kwarg = 'product_slug'
    template_name = 'product/delete.html'
    success_url = '/'
    queryset = Product.objects.all()

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        product_slug = self.kwargs.get('product_slug') or self.request.GET.get('product_slug')
        queryset = queryset.filter(slug=product_slug)
        obj = queryset.get()
        if obj.seller != self.request.user:
            raise Http404(_("You don't own this object"))
        return obj

templates/product/change.html
{% extends 'base.html' %}

{% block content %}
    <h2> Change exists advertisement </h2><br>
         <form method='post' enctype="multipart/form-data">
             {% csrf_token %}

             {{ form.as_p }}

         <input type="submit" value="Change product">
         </form>
{% endblock %}

 {% block pagination %}
 {% endblock %}


templates/product/create.html
{% extends 'base.html' %}

{% block content %}

    <h2>Create new product</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

        <input type="submit" value="Create product">
    </form>

{% endblock %}

 {% block pagination %}
 {% endblock %}

templates/product/delete.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

 {% block pagination %}
 {% endblock %}



templates/product/detail.html
{% extends 'base.html' %}
{% load static %}

 {% block content %}
     <div>
     <h2> Product details </h2>

     <h1>{{ product.title }} </h1><br>
     <img style="max-width: 300px; max-height: 300px" src="{% if product.image %}{{ product.image.url }}
              {% else %} {% static "img/no_image.png" %}{% endif %}"><br>
     <h3> {% if product.model %} Model: {{ product.model }} {% endif %}<br>
          Descriptions: {{ product.description }} <br>
          Price: ${{ product.price }} <br>
          {% if product.quantity > 1 %} Quantity: {{ product.quantity }} {% endif %}<br>
          Date of creation: {{ product.created |date:"d/M/Y"}}<br>
          Seller: {{ product.seller }} <br>
          Seller`s phone: {{ product.seller.phone_number }}<br>
          Seller`s email: {{ product.seller.email }}<br><br>

         {% if product.quantity > 1  %}
              <form action="{% url "cart:cart_add" product.slug %}" method="post">
                 {{ purchase_form.as_p }}
                 {% csrf_token %}
                 <input type="submit" value="Add to cart">
              </form>
              <br><br>
         {% else %}
             <form action="{% url "cart:cart_add" product.slug %}" method="post">
                {% csrf_token %}
             <input type="submit" value="Add to cart">
             </form>
             <br><br>
         {% endif %}


          {% if request.user == product.seller %}
              <form method='post' action="{% url 'product:change_product' product.slug %}">
              {% csrf_token %}
              <input type="button" value="Change product"
              onclick="window.location.href='{% url 'product:change_product' product.slug %}'">
              </form>
          {% endif %}

          {% if request.user == product.seller %}
              <form method='post' action="{% url 'product:delete_product' product.slug %}">
              {% csrf_token %}
              <input type="submit" value="Delete product">
              </form>
          {% endif %}

          {% if request.user != product.seller %}
              <form method='post' action="{% url 'favorites:create_favorites' product.slug %}">
              {% csrf_token %}
              <input type="submit" value="Add to favorites">
              </form>
          {% endif %}

          {% if comments %}
              <h3 style="color: red">Comments</h3>
              {% for comment in comments %}
              Content: {{ comment.content }}<br>
              Author: {{ comment.author }}<br><br>
              {% endfor %}
          {% endif %}

          {% if request.user != product.seller %}
              <h3 style="color:darkorange">Add comment</h3>
              <form action="{% url 'comment:create_comment' product.id%}" method="post">
              {% csrf_token %}
              {{ comment_form.as_p }}
              <input type="submit" value="Add comment">
              </form>
          {% endif %}

     </h3>
     </div>

    {% endblock %}

 {% block pagination %}
 {% endblock %}