cart/urls.py
from django.urls import path

from cart import views
from cart.views import CartAddView, CartRemoveView

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:product_slug>/', CartAddView.as_view(), name='cart_add'),
    path('remove/<slug:product_slug>/', CartRemoveView.as_view(), name='cart_remove'),
]

favorites/urls.py
from django.urls import path
from favorites.views import FavoritesCreateView, FavoritesListView, FavoritesDeleteView

app_name = 'favorites'

urlpatterns = [
    path('create/<slug:product_slug>/', FavoritesCreateView.as_view(), name="create_favorites"),
    path('list/', FavoritesListView.as_view(), name="list_favorites"),
    path('delete/<int:pk>/', FavoritesDeleteView.as_view(), name="delete_favorites"),
]


marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from custom_user.views import RegistrationNewUser
from django.conf import settings
from django.conf.urls.static import static
from main_app.views import MarketplaceListView, page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MarketplaceListView.as_view(), name="main_page"),
    path('user/', include('custom_user.urls', namespace='user')),
    path('product/', include('product.urls', namespace='product')),
    path('marketplace/', include('main_app.urls', namespace='marketplace')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('favorites/', include('favorites.urls', namespace='favorites')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

favorites/models.py
from django.db import models
from django.urls import reverse

from custom_user.models import CustomUser
from product.models import Product

# Create your models here.


class Favorites(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


favorites/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView
from django.utils.translation import gettext_lazy as _
from django.db.models import Q
from favorites.models import Favorites
from main_app.permission_mixins import UserLoginRequiredMixin
from product.models import Product


# Create your views here.


class FavoritesCreateView(UserLoginRequiredMixin, View):
    model = Favorites
    slug_url_kwarg = 'product_slug'
    success_url = '/'
    template_name = 'favorites/create.html'

    def post(self, request, *args, **kwargs):
        product = Product.objects.get(slug=self.kwargs['product_slug'])
        if Favorites.objects.filter(Q(user=self.request.user) & Q(product=product)).exists():
            return HttpResponseRedirect('/')
        Favorites(user=self.request.user, product=product).save()
        return HttpResponseRedirect('/')


class FavoritesListView(UserLoginRequiredMixin, ListView):
    model = Favorites
    template_name = 'favorites/list.html'   
    queryset = Favorites.objects.all()

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class FavoritesDeleteView(UserLoginRequiredMixin, DeleteView):
    model = Favorites
    pk_url_kwarg = 'pk'
    template_name = 'favorites/delete.html'
    success_url = '/favorites/list/'
    queryset = Favorites.objects.all()

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        pk = self.kwargs.get('pk') or self.request.GET.get('pk')
        queryset = queryset.filter(id=pk)
        obj = queryset.get()
        if obj.user != self.request.user:
            raise Http404(_("You don't own this object"))
        return obj



templates/favorites/create.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

 {% block pagination %}
 {% endblock %}

templates/favorites/delete.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

 {% block pagination %}
 {% endblock %}



templates/favorites/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <h3>List of favorites product</h3>

    {% for favorites in favorites_list %}
        <a href="{{ favorites.product.get_absolute_url }}">{{ favorites.product.title }} <br>
              <img style="max-width: 100px; max-height: 100px" src="{% if favorites.product.image %}
              {{ favorites.product.image.url }} {% else %} {% static "img/no_image.png" %}
              {% endif %}"></a><br>
              ${{ favorites.product.price }}<br><br>

              <form method='post' action="{% url 'favorites:delete_favorites' favorites.id %}">
              {% csrf_token %}
              <input type="submit" value="Delete from favorites">
              </form>
              <br>
    {% endfor %}

{% endblock %}

 {% block pagination %}
 {% endblock %}

